<?php

return [
    'regions' => [
        'North America',
        'Western Europe',
        'Eastern Europe',
        'Middle East',
        'Southeast Asia',
        'East Asia',
        'South Asia',
        'Africa',
        'South America',
        'Oceania',
        'Central America',
        'Caribbean',
    ],

    'countries' => [
        ['code' => 'US', 'name' => 'United States', 'export_market_region' => 'North America', 'geographic_region' => 'Americas'],
        ['code' => 'CA', 'name' => 'Canada', 'export_market_region' => 'North America', 'geographic_region' => 'Americas'],
        ['code' => 'MX', 'name' => 'Mexico', 'export_market_region' => 'North America', 'geographic_region' => 'Americas'],
        ['code' => 'DE', 'name' => 'Germany', 'export_market_region' => 'Western Europe', 'geographic_region' => 'Europe'],
        ['code' => 'FR', 'name' => 'France', 'export_market_region' => 'Western Europe', 'geographic_region' => 'Europe'],
        ['code' => 'GB', 'name' => 'United Kingdom', 'export_market_region' => 'Western Europe', 'geographic_region' => 'Europe'],
        ['code' => 'NL', 'name' => 'Netherlands', 'export_market_region' => 'Western Europe', 'geographic_region' => 'Europe'],
        ['code' => 'ES', 'name' => 'Spain', 'export_market_region' => 'Western Europe', 'geographic_region' => 'Europe'],
        ['code' => 'IT', 'name' => 'Italy', 'export_market_region' => 'Western Europe', 'geographic_region' => 'Europe'],
        ['code' => 'PL', 'name' => 'Poland', 'export_market_region' => 'Eastern Europe', 'geographic_region' => 'Europe'],
        ['code' => 'CZ', 'name' => 'Czech Republic', 'export_market_region' => 'Eastern Europe', 'geographic_region' => 'Europe'],
        ['code' => 'RO', 'name' => 'Romania', 'export_market_region' => 'Eastern Europe', 'geographic_region' => 'Europe'],
        ['code' => 'AE', 'name' => 'United Arab Emirates', 'export_market_region' => 'Middle East', 'geographic_region' => 'Asia'],
        ['code' => 'SA', 'name' => 'Saudi Arabia', 'export_market_region' => 'Middle East', 'geographic_region' => 'Asia'],
        ['code' => 'QA', 'name' => 'Qatar', 'export_market_region' => 'Middle East', 'geographic_region' => 'Asia'],
        ['code' => 'SG', 'name' => 'Singapore', 'export_market_region' => 'Southeast Asia', 'geographic_region' => 'Asia'],
        ['code' => 'MY', 'name' => 'Malaysia', 'export_market_region' => 'Southeast Asia', 'geographic_region' => 'Asia'],
        ['code' => 'TH', 'name' => 'Thailand', 'export_market_region' => 'Southeast Asia', 'geographic_region' => 'Asia'],
        ['code' => 'ID', 'name' => 'Indonesia', 'export_market_region' => 'Southeast Asia', 'geographic_region' => 'Asia'],
        ['code' => 'VN', 'name' => 'Vietnam', 'export_market_region' => 'Southeast Asia', 'geographic_region' => 'Asia'],
        ['code' => 'CN', 'name' => 'China', 'export_market_region' => 'East Asia', 'geographic_region' => 'Asia'],
        ['code' => 'JP', 'name' => 'Japan', 'export_market_region' => 'East Asia', 'geographic_region' => 'Asia'],
        ['code' => 'KR', 'name' => 'South Korea', 'export_market_region' => 'East Asia', 'geographic_region' => 'Asia'],
        ['code' => 'IN', 'name' => 'India', 'export_market_region' => 'South Asia', 'geographic_region' => 'Asia'],
        ['code' => 'PK', 'name' => 'Pakistan', 'export_market_region' => 'South Asia', 'geographic_region' => 'Asia'],
        ['code' => 'BD', 'name' => 'Bangladesh', 'export_market_region' => 'South Asia', 'geographic_region' => 'Asia'],
        ['code' => 'ZA', 'name' => 'South Africa', 'export_market_region' => 'Africa', 'geographic_region' => 'Africa'],
        ['code' => 'NG', 'name' => 'Nigeria', 'export_market_region' => 'Africa', 'geographic_region' => 'Africa'],
        ['code' => 'EG', 'name' => 'Egypt', 'export_market_region' => 'Africa', 'geographic_region' => 'Africa'],
        ['code' => 'BR', 'name' => 'Brazil', 'export_market_region' => 'South America', 'geographic_region' => 'Americas'],
        ['code' => 'AR', 'name' => 'Argentina', 'export_market_region' => 'South America', 'geographic_region' => 'Americas'],
        ['code' => 'CL', 'name' => 'Chile', 'export_market_region' => 'South America', 'geographic_region' => 'Americas'],
        ['code' => 'AU', 'name' => 'Australia', 'export_market_region' => 'Oceania', 'geographic_region' => 'Oceania'],
        ['code' => 'NZ', 'name' => 'New Zealand', 'export_market_region' => 'Oceania', 'geographic_region' => 'Oceania'],
        ['code' => 'GT', 'name' => 'Guatemala', 'export_market_region' => 'Central America', 'geographic_region' => 'Americas'],
        ['code' => 'PA', 'name' => 'Panama', 'export_market_region' => 'Central America', 'geographic_region' => 'Americas'],
        ['code' => 'JM', 'name' => 'Jamaica', 'export_market_region' => 'Caribbean', 'geographic_region' => 'Americas'],
        ['code' => 'DO', 'name' => 'Dominican Republic', 'export_market_region' => 'Caribbean', 'geographic_region' => 'Americas'],
    ],
];
